[book]
authors = ["Carro"]
language = "en"
multilingual = false
src = "src"
title = "bittensor-docs"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/opentensor/docs"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/opentensor/docs/edit/master/guide/{path}"
