version: 2.1
orbs:
  rust: circleci/rust@1.6.0

parameters:
  is_manual:
    type: string
    default: "no"

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/rust:1.64.0

    steps:
      - checkout
      - restore_cache:
          key: mdbook-cache
      - run:
          command: mdbook build
      - persist_to_workspace:
          root: book
          paths:
            - "*"

  deploy:
    resource_class: small
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
          - "0f:60:a5:03:4a:dd:26:05:91:3a:97:1e:be:c7:d4:f7"
          - "00:56:08:f6:9f:97:bd:3d:01:69:c0:30:e7:ec:cd:7a"
          - "5c:f4:a0:0f:70:dc:65:3f:a4:f7:0a:be:2c:5c:12:fa"
      - checkout
      - attach_workspace:
          at: book
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@3.0.0
            git config user.email "ci-build@opentensor.ai"
            git config user.name "ci-build"
      - run:
          name: Docs Bittensor Page
          command: echo $BT_DOCS_CNAME > ./book/CNAME
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --no-history --branch gh-pages --dist book

  build_mdbook:
    resource_class: large
    docker:
      - image: cimg/rust:1.64.0
    steps:
      - restore_cache: # save compute time if it already exists.
            key: mdbook-cache
      - run:
          name: Install mdbook
          command: cargo install mdbook
      - save_cache:
          key: mdbook-cache
          paths:
            - "~/.cargo"

workflows:
  build: 
    jobs: 
      - build:
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build

  make_cache:
    when:
      or:
        - equal: [ "build_mdbook", << pipeline.schedule.name >> ]
        - equal: [ "yes", << pipeline.parameters.is_manual >> ]
    jobs:
      - build_mdbook