version: 2.1
orbs:
  rust: circleci/rust@1.6.0


jobs:
  build:
    docker:
      - image: cimg/rust:1.61.0
    steps:
      - checkout
      - run: cargo --version

      - run: 
          name: install cargo & mdbooks
          command: | 
            cargo install cargo-update
            cargo install mdbook
            pwd && mdbook build
        
          



            

